### ISSUE TITLE
Есть идея что бы не нужно было специально скачивать firefox, для этой проги.

### ISSUE THREAD

**Issue by Transparency010101** [yasharusakov/automatic_passing_of_test#20]
Я 100% помню, я видел что можно скачать driver firefox и положить его в католог с кодом, оно будет работат.
https://www.youtube.com/watch?v=r4OY7hp4yd8&list=PLqGS6O1-DZLp1kgiQNpueIMCHRNzgHa1r&index=2 timecode 2:17

**Comment by yasharusakov** [comment]
Идея хорошая

**Comment by Transparency010101** [comment]
Этим я займусь

**Comment by Transparency010101** [comment]
Мне лень этим заниматься, и особо смысла нету. Только мы вдвоем этой прогой пользуемся.
