### ISSUE TITLE
Может стоит стделать тесты?

### ISSUE THREAD

**Issue by Transparency010101** [yasharusakov/automatic_passing_of_test#7]
Что думаешь на этот счет , Яша?.

**Comment by yasharusakov** [comment]
обезательно

**Comment by Transparency010101** [comment]
Я с этим попробую разобраться в четверг или пятницу.

**Comment by yasharusakov** [comment]
мне кажеться тесты уже не нужны

**Comment by yasharusakov** [comment]
Они делаютсья помощью jest и у него есть cli

**Comment by Transparency010101** [comment]
Окай, их нужно сделать 100%
